name: CI/CD Pipeline
run-name: ${{ github.actor }} is learning Github Actions

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'

            - name: Install Dependencies
              run: |
                 python -m pip install --upgrade pip
                 pip install -r requirements.txt

            - name: Run tests
              run: |
                pytest tests/
            
            - name: Run Lint
              run: |
                pip install flake8
                flake8 module/ tests/
              continue-on-error: true
     
    DEV:
      name: Deploy to Dev
      if: github.event_name == 'pull_request'
      needs: [build]
      runs-on: ubuntu-latest
      environment:
        name: DEV
        url: 'http://dev.mymodel.endpoint'
      steps:
        - name: Deploy
          run: echo I am deploying to dev